#!/usr/bin/env python3



import sys

from mpi4py import MPI
import numpy as np
import adios2
import plxr

from PIL import Image

## viewer.py
usage_msg = """Usage: extract.py <bp-file-name> <image-name>

Produces a series of images from the timesteps of the named variable
"""

def main():

    step = 0

    # Single process viewer
    comm = MPI.COMM_SELF

    if len(sys.argv) < 3:
        print (usage_msg)
        exit(0)

    bpfilename = sys.argv[1]
    varname = sys.argv[2]


    #Open the bpfile
    with adios2.open(bpfilename, "r", comm) as fh:
        pimg = plxr.read_image (fh, varname, step)
        pimg.save("%s_%i.png"%(varname, step) )
        step = step + 1



if __name__ == "__main__":
    main()
